#pragma once

#define NXLIB_VERSION_YEAR   19
#define NXLIB_VERSION_MONTH  12
#define NXLIB_VERSION_DAY    4

#define NXLIB_VERSION_MAJOR  2
#define NXLIB_VERSION_MINOR  3
#define NXLIB_VERSION_BUILD  1174
